# GetPolicy.srv
# Get policy model

# Request
---
# Response
string model_path                   # Model path
string algorithm                    # Algorithm type
float32[23] policy_mean            # Policy mean
float32[23] policy_std             # Policy standard deviation
